### ISSUE TITLE
How to link to appendices?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/pfmc_assessment_handbook#10]
I attempted to replace "ADD LINK" with a link to Appendix A in recent commits following guidance at https://quarto.org/docs/books/book-crossrefs.html#creating-references and discussion at https://community.rstudio.com/t/quarto-how-to-cross-reference-unnumbered-book-chapter/136279/3. However, the best I had was a link to "Chapter 6" and the current result looks like the following:

> 1.4.2 At-Sea Hake Observer Program (ASHOP)
Vanessa Tuttle (Vanessa.Tuttle@noaa.gov) is the contact person for this. Unlike the shoreside subset of the hake fishery which has dockside sampling and bycatch reported in PacFIN, the observed bycatch in the at-sea sectors (motherships and catcher-processors) is reported to the NORPAC database housed at AFSC. A non-definitive list of “common” and “uncommon” species seen in the hake fishery (as of 2008, but Vanessa says it is still current as of 2022) is in ?sec-AppendixA of this document.

I'm not sure what the role of {.appendix} is at the top of the appendix and am clearly failing to reference it appropriately.

@okenk, can you help?

**Comment by okenk** [comment]
I also found the Quarto manual quite unhelpful! I tried a bunch of different things. Many did not work. I think I got it working with 0c0555a6c000723ba1e131682e1cc217cd350d2d. The syntax I used was `[Appendix -@sec-appendixA]`.

I don't think `{.appendix}` was doing anything. I fiddled a bit with the yml file and now they show up as proper appendixes instead of as the last two chapters.

**Comment by kellijohnson-NOAA** [comment]
For what it is worth, the `{.appendix}` is only meant to be used after the title of a section header for text that is in the main body. Where we are listing the appendices in the yaml header and using separate files instead.

For example,
```
## This is a normal header

Some text

## appendix a {.appendix}

This text will be moved to the end of the document and placed in an appendix

## Second normal header

This text will appear before appendix a. This functionality allows you to place information
that you want in an appendix close to the information that it actually pertains to while
you are typing.
```
