### ISSUE TITLE
debug github actions

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/pfmc_assessment_handbook#11]
I made a small change to the manual (updating broken link, revising text) and the github action to build the handbook failed. It still failed after I reverted the change I made, indicating that the problem is something that changed in the actions or their dependencies since 4 November 2022 when we last had a successful build: https://github.com/pfmc-assessments/pfmc_assessment_handbook/actions.

The error is:
```
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 8, columns 3--18) property name number-sections is invalid
7:   date: last-modified
8:   number-sections: true
    ~~~~~~~~~~~~~~~~
ℹ The error happened in location book:number-sections.
```

@okenk, can you take a look?

**Comment by okenk** [comment]
@iantaylor-NOAA, you can reproduce this error on your own computer if you update to the latest version of quarto (which is, unsurprisingly, what the GitHub Action uses).

**Comment by okenk** [comment]
Hmm, so I fixed the error you were getting, but now there is a new error and I am completely befuddled...

**Comment by iantaylor-NOAA** [comment]
Thank you for looking at this @okenk. I don't understand it either. 
I just updated my Quarto to v1.2.313 and was able to render the html just fine locally where the html source confirms that the new version was used: `<meta name="generator" content="quarto-1.2.313">`.

**Comment by okenk** [comment]
Yeah, after f406dea8d587107426df59d57ae23419bb3b54fd I am also able to render locally just fine, which is making it hard to debug. I put in [an issue to the quarto github action repo](https://github.com/quarto-dev/quarto-actions/issues/64), hopefully they will not think I am a complete dolt.

**Comment by okenk** [comment]
Woo hoo, [it is working again](https://github.com/pfmc-assessments/pfmc_assessment_handbook/actions/runs/3972117180)!

**Comment by iantaylor-NOAA** [comment]
Thank you @okenk!

For future reference, I think it's worth noting that the problem was created by a change at the Quarto end of things and the solution was to change "NWFSC/SWFSC" to "NWFSC and SWFSC" in the title as discussed in this issue that @okenk wisely posted to the quarto developers: https://github.com/quarto-dev/quarto-actions/issues/64.

It sounds like they will support having a "/" in the title in the future, but I think we can stick with the "and" going forward and not bother trying to bring it back in some future version.

**Comment by okenk** [comment]
I did try deleting the slash once and [it still failed](https://github.com/pfmc-assessments/pfmc_assessment_handbook/actions/runs/3971978665). But then a few minutes later it worked. I assume some changes were being made on the quarto end or something. 🤷
