### ISSUE TITLE
Consider linking to nmfs-opensci resources

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [pfmc-assessments/pfmc_assessment_handbook#15]
Hi - I am always impressed when I visit the [nmfs opensci org](https://github.com/orgs/nmfs-opensci/repositories) how many useful templates there are for websites, quarto, Rmd docs and presentations and we're thinking about how to make those more discoverable. It could be useful to link to from the assessments handbook so folks are aware of these resources when they start working on stuff!

Thanks for considering

**Comment by okenk** [comment]
I think we probably intentionally do not want to add NMFS branding on the handbook itself because we don't want it to look official, but I added it as [additional useful resource](https://github.com/pfmc-assessments/pfmc_assessment_handbook/blob/main/05-other.qmd)

**Comment by ChristineStawitz-NOAA** [comment]
thanks! I was just thinking of linking to the resources, not branding this handbook :)
