### ISSUE TITLE
deprecate google doc version of the handbook

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/pfmc_assessment_handbook#2]
@okenk, it looks like all the changes to the Google Doc have been brought into this github version.
If so, we could wipe out the contents of the Google Doc and just replace it with a note to come to this repo and page instead.

**Comment by okenk** [comment]
Sounds good to me.

**Comment by iantaylor-NOAA** [comment]
I spoke too soon. We should resolve the comments or migrate them into github issues first.

**Comment by iantaylor-NOAA** [comment]
I transferred the remaining comments and assignments to github issues #3 through #8 and named the version in the Google Doc version history as "Final state before moving to github" but haven't yet wiped out the Google Doc in case anyone wants a final look. We can wipe it out next week.

**Comment by iantaylor-NOAA** [comment]
Google Doc now wiped out and replaced with the following text:
> The handbook has been moved to https://pfmc-assessments.github.io/pfmc_assessment_handbook/
>
> Changes to the text can be made via that link or within the related github repository: https://github.com/pfmc-assessments/pfmc_assessment_handbook
> 
> This Google Doc can be retained for a while to provide the links above and for access to the version history should that ever be needed in the future.
