### ISSUE TITLE
update "Stuff to do well in advance of peak stock assessment season"

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/pfmc_assessment_handbook#4]
@chantelwetzel-noaa, you self-assigned this issue in the Google Doc.
I added this comment to your assignment comment:
> Note that this old Google Doc includes an attempt to list stuff for this section this: [https://docs.google.com/document/d/1KIjS8yBqYnfSg_X1_l6nhuMxtylivKCzd6I6Q87FdUI/edit#heading=h.aok2jgtxly1j](https://www.google.com/url?q=https://docs.google.com/document/d/1KIjS8yBqYnfSg_X1_l6nhuMxtylivKCzd6I6Q87FdUI/edit%23heading%3Dh.aok2jgtxly1j&sa=D&source=docs&ust=1664570637154973&usg=AOvVaw0EsNqeVA_8XVqxtW0RNqI0)

markdown text is here https://pfmc-assessments.github.io/pfmc_assessment_handbook/05-other.html#stuff-to-do-well-in-advance-of-peak-stock-assessment-season
rendered here:
https://pfmc-assessments.github.io/pfmc_assessment_handbook/05-other.html#stuff-to-do-well-in-advance-of-peak-stock-assessment-season

**Comment by chantelwetzel-noaa** [comment]
Hmm. I updated in the google doc. I will move over the new edit
