### ISSUE TITLE
Update info on GEMM

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/pfmc_assessment_handbook#9]
The "Notes and best practices for observer data and discards" (at 
https://pfmc-assessments.github.io/pfmc_assessment_handbook/01-data-sources.html#notes-and-best-practices-for-observer-data-and-discards) is really thorough and seems mostly up to date in spite of seemingly having last been updated in 2019.

However, it would benefit from a couple things related to the Groundfish Expanded Mortality Multiyear (GEMM) data.

First, the new `nwfscSurvey::pull_gemm()` function for getting GEMM data (yay!) should be noted.

Second, it would be good to say something about how to use GEMM data when discards are modeled as a rate (alternative 3 in that section), so the GEMM data isn't used directly. During the 2021 lingcod STAR a big difference in total mortality estimated from the northern model and the GEMM estimate was noted (discussed in https://github.com/pfmc-assessments/lingcod/issues/155). Some differences will always exist due to imperfect fits to discard rates and discard mean weights, as well as different assumptions that go into the GEMM calculations from what's assumed in our models, but it would have been better to do a comparison before the review and either modify the model to reduce the difference or provide a satisfactory explanation for why it was large.

@chantelwetzel-noaa, do you want to work on this, have me work on it, or suggest someone else? You may notice other areas that need update than the two that I mention above.

**Comment by chantelwetzel-noaa** [comment]
@iantaylor-NOAA thanks for linking our email discuss to the information within the handbook.  I will be happy to update this section and to provide some initial guidance on how these data should be used.
